name: CI

on:
  push:
  pull_request:

jobs:
  build-on-ubuntu1804:
    runs-on: ubuntu-18.04
    env:
      RUNS_ON: ubuntu1804
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.24.x'
    - name: Test cmake version
      run: cmake --version
    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          freeglut3-dev \
          g++ \
          libcurl4-openssl-dev \
          libfontconfig-dev \
          libgl1-mesa-dev \
          libgtk2.0-dev \
          mesa-common-dev \
          unzip
    - name: Get GCC version
      run: gcc --version
    - name: Get libc version
      run: ldd --version

    - name: Install wxWidgets
      run: |
        sudo apt-get install -y libwxgtk*-dev
        sudo ln -s $(which wx-config) /usr/local/bin/wx-config-3
        wx-config-3 --cflags | grep I

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build LK
      run: |
        cmake -Bbuild_linux -DCMAKE_BUILD_TYPE=Debug
        cmake --build build_linux -- -j

    - name: Save static lib & lksandbox
      uses: actions/upload-artifact@v2
      with:
        name: LK-${{ env.RUNS_ON }}-x86_64
        path: |
          build_linux/lk_sandbox*
          build_linux/lk*.a

  build-on-ubuntu2004:
    runs-on: ubuntu-20.04
    env:
      RUNS_ON: ubuntu2004
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.24.x'
    - name: Test cmake version
      run: cmake --version
    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          freeglut3-dev \
          g++ \
          libcurl4-openssl-dev \
          libfontconfig-dev \
          libgl1-mesa-dev \
          libgtk2.0-dev \
          mesa-common-dev \
          unzip
    - name: Get GCC version
      run: gcc --version
    - name: Get libc version
      run: ldd --version

    - name: Install wxWidgets
      run: |
        sudo apt-get install -y libwxgtk*-dev
        sudo ln -s $(which wx-config) /usr/local/bin/wx-config-3
        wx-config-3 --cflags | grep I

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build LK
      run: |
        cmake -Bbuild_linux -DCMAKE_BUILD_TYPE=Debug
        cmake --build build_linux -- -j

    - name: Save static lib & lksandbox
      uses: actions/upload-artifact@v2
      with:
        name: LK-${{ env.RUNS_ON }}-x86_64
        path: |
          build_linux/lk_sandbox*
          build_linux/lk*.a
